### ISSUE TITLE
Problem with submit

### ISSUE THREAD

**Issue by cwytko** [tripal/tripal_galaxy#1]
Currently on the tripal_galaxy.module file I have the hook alter set up to reroute the submit button from ANY webform to the custom tripal galaxy workflow exec, this needs to be fixed as webforms will/may be used more extensively in the future (the idea is to create a new node type that will be galaxy specific)

**Comment by spficklin** [comment]
Fixed... The execution is handled separately form the form submit.  A cron will execute the jobs.
