### ISSUE TITLE
Workflow invocation error handling

### ISSUE THREAD

**Issue by cwytko** [tripal/tripal_galaxy#10]
The workflow(s) are not being launched after the submission is pressed.
**This needs to be fixed first**

**Comment by spficklin** [comment]
They don't get launched automatically.  They must be launched via cron or via a drush command.

**Comment by cwytko** [comment]
I'm looking at my database on the tripal_galaxy_workflow_submission table and the status is **error**
**Error**:
`The following parameters for function GalaxyWorkflows::invoke() are required: input_dataset_ids.
`

This is good news! **The job is launching** hence the title change. **AND** a workflow history was created on job launch (the suffix of the name of the history matched the submit_date column on the table) so that was fine too. 

The problem is error handling which is uncaught.

**Comment by spficklin** [comment]
Jobs are now submitted via the Tripal Jobs system. Tested and working
