### ISSUE TITLE
unable to view results because of 'Waiting' job status

### ISSUE THREAD

**Issue by MingChen0919** [tripal/tripal_galaxy#101]
This issue is found on the test galaxy (https://test-galaxy.bioinfo.wsu.edu/). The production galaxy works fine.

The jobs are complete but the job status won't change from **waiting** to **complete**. I have manually run `drush trp-galaxy-status --submission=ID` many times but it didn't change the status.

<img width="990" alt="screen shot 2018-06-01 at 11 25 18 pm" src="https://user-images.githubusercontent.com/1262709/40869980-55d847ec-65f3-11e8-9781-11548b927419.png">

To reproduce this issue, the following workflow can be imported into the test galaxy instance.

[sequence-quality-control-single-end.ga.zip](https://github.com/tripal/tripal_galaxy/files/2064644/sequence-quality-control-single-end.ga.zip)

**Comment by MingChen0919** [comment]
**This might be a galaxy instance issue.**

Here is the json data for a complete history: https://test-galaxy.bioinfo.wsu.edu/api/histories/2d83f137e3015847. The **state** is "ok".

And here is the json data for the same invocation: https://test-galaxy.bioinfo.wsu.edu/api/workflows/6dbc21d257b88b00/invocations/df6be339a52c816d. The **state** for each step is "scheduled".

**It seems the galaxy instance failed to update the state for invocations**. But the tripal galaxy module seems extracting state info from invocations instead of history.

**Comment by spficklin** [comment]
I have duplicated this behavior on the test server.  I don't know what causes it. I put in an issue for Heidi at  bcuser30/ML_GalaxyQueue#8

**Comment by MingChen0919** [comment]
Hi @spficklin , from today's DIBBs meeting. It seems that you might have misunderstood my problem here. So, I created the figure below to make my problem less confusing.

<img width="1403" alt="screen shot 2018-06-08 at 3 53 43 pm" src="https://user-images.githubusercontent.com/1262709/41178722-2e137996-6b36-11e8-8598-e16b601ef108.png">

**Comment by MingChen0919** [comment]
~~Hi @spficklin , I got some help from John Chilton who developed the galaxy workflow API. He said that with the new version (18.05), we should use the jobs api to get the job state, instead of the workflow invocation API. I tested that and it worked for me.~~ 

~~basically, we should use the invocation api to get the job ids, and then check the job state by using the job ids and call the job api(in galaxy it is **api/jobs/[jobs_id]**, but i don't know if blend4php has an interface to it).~~

ok, I think i made a mistake. The tripal galaxy module actually does use the jobs api. The waiting issue is caused by the job_id from each invocation results and by the wrong job state. The job_ids all have value NULL.

Maybe we can determine job state by checking the state of history contents using the history API `api/histories/[history_id]/contents`?

**Comment by MingChen0919** [comment]
ok, I think i made a mistake. The tripal galaxy module actually does use the jobs api. The waiting issue is caused by the job_id from each invocation results and by the wrong job state. The job_ids all have value NULL.

**Comment by MingChen0919** [comment]
Here is some inputs from John Chilton: https://github.com/galaxyproject/galaxy/issues/6479.

**Comment by spficklin** [comment]
Thanks Ming.  Can you clarify what you mean by 

> The waiting issue is caused by the job_id from each invocation results and by the wrong job state. The job_ids all have value NULL.

Is the job_id NULL in what Galaxy returns?

**Comment by MingChen0919** [comment]
When I run `api/workflows/<workflow_id>/invocations/<invocation_id>/steps/<invocation_step_id>`, the `job_id` value from some steps are `NULL`.  Then I can't use the api `/api/jobs/<job_id>` to get the job information. Even for some cases when the job_id is available, the job state is incorrect.

**Comment by MingChen0919** [comment]
Hi @spficklin , John Chilton added a PR to restore the ability to track job states. Check this: https://github.com/galaxyproject/galaxy/pull/6559.

**Comment by spficklin** [comment]
great news!

**Comment by MingChen0919** [comment]
I couldn't get john PR's to work. However, I was able to fix this issue from our side. The fix is on branch `fix_101_waiting_issue`.

The idea is to check job status from history directly. This information can be obtained from `/api/histories/[history_id]`, like below:

<img width="642" alt="screen shot 2018-08-19 at 6 33 27 pm" src="https://user-images.githubusercontent.com/1262709/44313916-c6e89a80-a3de-11e8-8405-1652dddcd2bb.png">

In the **state_details** array, if the **"ok" state has value larger than zero and all other states are zeros**, then the history completes successfully. We pull the history content and display it. 

This fix also handles error jobs. Below is how the result page look like:

<img width="1050" alt="screen shot 2018-08-19 at 7 19 27 pm" src="https://user-images.githubusercontent.com/1262709/44314285-04e8bd00-a3e5-11e8-95b8-de905cd3f7fa.png">

**Comment by shawnawsu** [comment]
@MingChen0919  I merged your pull request after testing, thanks for this!
