### ISSUE TITLE
Galaxy "Waiting" Status is accompanied by "View Results" link, which is confusing

### ISSUE THREAD

**Issue by mestato** [tripal/tripal_galaxy#108]
Title is pretty self explanatory. I think it would be less confusing if the "View results" link didn't appear until the Galaxy status is "completed". And if the galaxy status is "Error" then the link should say "View error message" and maybe also be accompanied by a "Report Error to Get Help". @MingChen0919 is this something you could work on and PR?

**Comment by shawnawsu** [comment]
@mestato We just merged in a fix for this issue. Now users will not see 'View Results' unless the workflow has completed successfully and they will see 'View Error' if the workflow returned an error.
