### ISSUE TITLE
Issue with Input dataset tool vanilla

### ISSUE THREAD

**Issue by cwytko** [tripal/tripal_galaxy#11]
Weird error during webform construction 
`case 'data_input' :
        // Make a fake tool and input so we can add the component for a
        // data_input step.
        $tool = array(
          'id' => NULL,
          'name' => $step['tool_inputs']['name'],
        );
        $input = array(
          'name' => $step['tool_inputs']['name'],
          'full_name' => $step['tool_inputs']['name'],
          'type' => 'data_input',
        );`
If the input data set tool is brought in vanilla (meaning that the workflow was not imported) (even with the label changed which is where the 'name' element should be set)
There is this bizarre error of the 'name' element not being set causing an error to the webform construction and disallowing the the workflow from being inserted to the site.

**Comment by cwytko** [comment]
This is a compatibility issue 
Something that has changed since galaxy bundles their workflows differently and now we need to work with that

**Comment by spficklin** [comment]
I think this is fixed as we are able to handle this with no issues now.
