### ISSUE TITLE
workflow end time and complete status is confusing

### ISSUE THREAD

**Issue by MingChen0919** [tripal/tripal_galaxy#120]
From the tripal jobs page, I can see that my workflow is complete and it has a submitted, start and end times. But my workflow is still running in Galaxy.

<img width="1211" alt="screen shot 2018-10-12 at 10 48 01 am" src="https://user-images.githubusercontent.com/1262709/46876487-756ff100-ce0c-11e8-9236-9dc8c6eb1122.png">

<img width="288" alt="screen shot 2018-10-12 at 10 50 07 am" src="https://user-images.githubusercontent.com/1262709/46876550-9b959100-ce0c-11e8-90c1-b7c69c850542.png">

Does tripal galaxy identifies a workflow as 'completed' if all inputs have successfully been transferred to Galaxy no matter whether the job is actually completed or not?

**Comment by spficklin** [comment]
This has been fixed in the current 7.x-1.x branch.  I saw the problem fixed it and didn't realize we had an issue for it, so there is no corresponding pull request.
