### ISSUE TITLE
Duplicated description on input fields

### ISSUE THREAD

**Issue by MingChen0919** [tripal/tripal_galaxy#121]
Descriptions on input fields in the workflow are duplicated. See the image below:

<img width="709" alt="screen shot 2018-10-16 at 2 02 25 pm" src="https://user-images.githubusercontent.com/1262709/47037362-bb9abc80-d14c-11e8-9372-06aa651b7ae4.png">

**Comment by MingChen0919** [comment]
Hi @spficklin , here is a workflow you can use to test.

[differential-expression-deseq2-analysis.ga.zip](https://github.com/tripal/tripal_galaxy/files/2497175/differential-expression-deseq2-analysis.ga.zip)

**Comment by spficklin** [comment]
Hi @MingChen0919.  I tried to install that workflow into my local Galaxy and I get this error message:

```
Step 3: testtoolshed.g2.bx.psu.edu/repos/mingchen0919/aurora_deseq2/aurora_deseq2_report/2.2.2 
     Tool is not installed.
```
It's been a while since you posted this so I'm curious if there has been a change?

**Comment by MingChen0919** [comment]
Hi @spficklin , the tool has new version. I just installed the new version in the WSU galaxy. I was able to import the workflow without any error.

**Comment by spficklin** [comment]
Thanks! I tested your PR for this and it works just fine and I agree it was the best fix.  Thanks for submitting!
