### ISSUE TITLE
Admin panel

### ISSUE THREAD

**Issue by mestato** [tripal/tripal_galaxy#125]
An admin panel for the module would be awesome. It could give an admin important Galaxy usage statistics, such as current queued workflow loads, number of active users, total storage used, workflow successes/errors, etc.

**Comment by spficklin** [comment]
Hi @mestato we have something similar to that already.  If you go to 
Admin > Tripal >Extensions > Galaxy and click on the usage tab.   Can take a look on your site and see if it meets your expectations?

**Comment by spficklin** [comment]
Here's a screenshot of my development server (very skimpy because I haven't done much) but gives you the idea

![screenshot from 2018-11-29 21-25-08](https://user-images.githubusercontent.com/1719352/49270256-527db880-f41d-11e8-82c0-6b7cfb557cee.png)

**Comment by spficklin** [comment]
Looks like we need to work on the text orientation at the bottom of the charts.... or turn them horizontally.

**Comment by mestato** [comment]
Sorry we missed that somehow! Thanks for pointing it out :)

**Comment by spficklin** [comment]
Great. I'm going to re-open this so we can fix the axis labels on those graphs.

**Comment by spficklin** [comment]
Another problem with these charts is they relay on the tripal_galaxy_workflow_submission table and expired workflows drop out after a period of time.  This means the tables only show results from the current time period not the full historical record.

**Comment by spficklin** [comment]
Graphs have been rotated to make them more legible

![image](https://user-images.githubusercontent.com/1719352/49487488-74998100-f7f7-11e8-9e49-4c6b4810185b.png)
