### ISSUE TITLE
Upload multiple files as a data collection

### ISSUE THREAD

**Issue by MingChen0919** [tripal/tripal_galaxy#13]
When executing a galaxy workflow, galaxy builds working instance for each input file.  For example, if I do a one-factor-two-levels deseq2 analysis, and I have 3 counts files for each level, galaxy will split the job into 3 independent deseq2 analysis jobs. Galaxy handles this issue by grouping files into data collections. The module may need to provide the functionality of uploading files into a data collection object.

**Comment by spficklin** [comment]
This has been resolved this weekend.  Pull to get the must recent development code.
