### ISSUE TITLE
Discrepency between Tool inputs on Galaxy vs inputs available on Tripal

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal_galaxy#139]
### System information

* Tripal Version: 7.x-3.0
* Drupal Version: 7.61
* PostgreSQL Version: 9.5.7
* PHP Version: 7.0.29

### Issue description

When a given tool on Galaxy has multiple selectable options (non-radio checkboxes), the same input on the Tripal side only provides a drop-down option where exactly 1 option is selectable

#### Steps to reproduce

Have a Galaxy workflow which uses a tool that allows multiple options, for example the built-in Line/Word/Character count.
Import the workflow into Tripal Galaxy and try to run the workflow
A dropdown menu is presented instead of a list of checkboxes 
#### Error messages and screenshots

![galaxydisc](https://user-images.githubusercontent.com/9593623/50176598-d8c74500-02cd-11e9-8cdc-b056b81a92cf.png)

The Galaxy workflow used in the test and in screenshot:
[Galaxy-Workflow-Scratch_Test.ga.zip](https://github.com/tripal/tripal_galaxy/files/2691939/Galaxy-Workflow-Scratch_Test.ga.zip)

**Comment by spficklin** [comment]
Hi @Ferrisx4 are you still experiencing this problem?

**Comment by Ferrisx4** [comment]
Yes @spficklin 
Tried on a fresh install of Drupal and Galaxy

**Comment by spficklin** [comment]
Hi @Ferrisx4 . My apologies this took so long to fix. I have just posted an update to the code that will give a multi-select drop down in these cases.  I'm going to close out the issue, but if you continue to have problems please post and we can reopen it.
