### ISSUE TITLE
workflow adding fails if there is data_collection_input step in the workflow

### ISSUE THREAD

**Issue by MingChen0919** [tripal/tripal_galaxy#14]
See the error message in the screenshot:

<img width="1157" alt="screen shot 2017-07-11 at 9 54 55 am" src="https://user-images.githubusercontent.com/1262709/28071907-58975a92-661f-11e7-8c82-e495a6235687.png">

**Comment by spficklin** [comment]
Fixed.  Data collections are now supported.
