### ISSUE TITLE
API to get submission ID

### ISSUE THREAD

**Issue by NicHerndon** [tripal/tripal_galaxy#142]
In order to retrieve results from Galaxy, we need a submission (or submission ID to use with tripal_galaxy_get_submission and get the submission).

Is there an API call to get a submission or a list of submissions based on the user ID?

**Comment by NicHerndon** [comment]
Actually, this might be addressed by fixing issue #141. I'm assuming once that is fixed, there will be a link to view results, with the submission ID in it.

**Comment by spficklin** [comment]
I believe PR #144 fixes this. The PR is merged.  Please comment if the problem persists.

There is now a new function:  `tripal_galaxy_get_user_submissions`

**Comment by spficklin** [comment]
Thanks @shawnawsu for the  fix!
