### ISSUE TITLE
tripal_galaxy_get_datasets seems to return too much data

### ISSUE THREAD

**Issue by NicHerndon** [tripal/tripal_galaxy#143]
I'd like to provide links to the users to download the results of a Galaxy workflow. I used `tripal_galaxy_get_datasets` to get the datasets, however, this structure seems to contain too much information (if I use `dpm` to look at its contents, the form hangs on loading the data).

The output generated with `dprint_r($datasets)` has 26,058 lines.

**Comment by shawnawsu** [comment]
Is this not working for you? https://tripal-galaxy.readthedocs.io/en/latest/API/api_overview.html#option-2-providing-download-links-for-users

**Comment by NicHerndon** [comment]
This is the file it returns.

Array
(
    [0] => Array
        (
            [accessible] => 1
            [type_id] => dataset-6468d854b6055777
            [resubmitted] => 
            [create_time] => 2019-01-12T00:46:42.631251
            [creating_job] => 41229eb3e3db4ff6
            [dataset_id] => f9abab74cfb07ec2
            [file_size] => 164
            [file_ext] => tabular
            [id] => 6468d854b6055777
            [misc_info] => uploaded tabular file
            [hda_ldda] => hda
            [download_url] => /galaxy/api/histories/1b65034869916c70/contents/6468d854b6055777/display
            [state] => ok
            [metadata_comment_lines] => 
            [display_types] => Array
                (
                )

            [display_apps] => Array
                (
                )

            [metadata_dbkey] => ?
            [type] => file
            [metadata_column_types] => Array
                (
                    [0] => str
                    [1] => int
                    [2] => int
                    [3] => float
                    [4] => int
                    [5] => int
                )

            [misc_blurb] => 7 lines
            [peek] => <table cellspacing="0" cellpadding="3"><tr><th>1</th><th>2</th><th>3</th><th>4</th><th>5</th><th>6</th></tr><tr><td>NAME</td><td>ENV1</td><td>ENV2</td><td>ENV3</td><td>ENV4</td><td>ENV5</td></tr><tr><td>ID1</td><td>46</td><td>972</td><td>236</td><td>230</td><td>132</td></tr><tr><td>ID2</td><td>32</td><td>987</td><td>238</td><td>232</td><td>83</td></tr><tr><td>ID3</td><td>32</td><td>987</td><td>238</td><td>232</td><td>83</td></tr><tr><td>ID4</td><td>32</td><td>987</td><td>NaN</td><td>232</td><td>83</td></tr></table>
            [update_time] => 2019-01-12T00:47:43.995377
            [data_type] => galaxy.datatypes.tabular.Tabular
            [tags] => Array
                (
                )

            [deleted] => 1
            [history_id] => 1b65034869916c70
            [metadata_column_names] => 
            [meta_files] => Array
                (
                )

            [genome_build] => ?
            [hid] => 23
            [model_class] => HistoryDatasetAssociation
            [metadata_data_lines] => 7
            [annotation] => 
            [permissions] => Array
                (
                    [access] => Array
                        (
                        )

                    [manage] => Array
                        (
                        )

                )

            [history_content_type] => dataset
            [name] => 20190111_194641_11_env_data.tsv
            [extension] => tabular
            [visible] => 1
            [url] => /galaxy/api/histories/1b65034869916c70/contents/6468d854b6055777
            [metadata_columns] => 6
            [uuid] => f76f114e-4332-4f95-93f8-b304b582a9bf
            [visualizations] => Array
                (
                    [0] => Array
                        (
                            [description] => Renders a horizontal bar diagram using NVD3 hosted at http://www.nvd3.org.
                            [embeddable] => 
                            [href] => /galaxy/plugins/visualizations/nvd3_horizontal/show
                            [entry_point] => Array
                                (
                                    [type] => chart
                                    [attr] => Array
                                        (
                                            [load] => nvd3_horizontal
                                            [src] => ../../nvd3_bar/static/nvd3.js
                                            [css] => ../../nvd3_bar/static/nvd3.css
                                        )

                                    [file] => 
                                )

                            [groups] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => color
                                            [name] => color
                                            [label] => Pick a series color
                                        )

                                    [1] => Array
                                        (
                                            [is_label] => true
                                            [type] => data_column
                                            [name] => tooltip
                                            [is_auto] => true
                                            [label] => Data point labels
                                        )

                                    [2] => Array
                                        (
                                            [placeholder] => Data label
                                            [type] => text
                                            [name] => key
                                            [value] => Data label
                                            [label] => Provide a label
                                        )

                                    [3] => Array
                                        (
                                            [is_label] => true
                                            [type] => data_column
                                            [name] => x
                                            [is_auto] => true
                                            [label] => Values for x-axis
                                        )

                                    [4] => Array
                                        (
                                            [is_numeric] => true
                                            [type] => data_column
                                            [name] => y
                                            [label] => Values for y-axis
                                        )

                                )

                            [logo] => ./static/plugins/visualizations/nvd3/nvd3_horizontal/static/logo.png
                            [specs] => Array
                                (
                                    [exports] => Array
                                        (
                                            [0] => png
                                            [1] => svg
                                            [2] => pdf
                                        )

                                    [tag] => svg
                                    [use_panels] => optional
                                )

                            [target] => galaxy_main
                            [name] => nvd3_horizontal
                            [title] => 
                            [settings] => Array
                                (
                                    [0] => Array
                                        (
                                            [help] => Provide a label for the axis.
                                            [placeholder] => Axis label
                                            [label] => X-Axis label
                                            [type] => text
                                            [value] => X-axis
                                            [name] => x_axis_label
                                        )

                                    [1] => Array
                                        (
                                            [test_param] => Array
                                                (
                                                    [help] => Select the value type of the axis.
                                                    [data] => Array
                                                        (
                                                            [0] => Array
                                                                (
                                                                    [value] => hide
                                                                    [label] => -- Do not show values --
                                                                )

                                                            [1] => Array
                                                                (
                                                                    [value] => auto
                                                                    [label] => Auto
                                                                )

                                                            [2] => Array
                                                                (
                                                                    [value] => d
                                                                    [label] => Integer
                                                                )

                                                            [3] => Array
                                                                (
                                                                    [value] => e
                                                                    [label] => Exponent
                                                                )

                                                            [4] => Array
                                                                (
                                                                    [value] => f
                                                                    [label] => Float
                                                                )

                                                            [5] => Array
                                                                (
                                                                    [value] => p
                                                                    [label] => Percent
                                                                )

                                                            [6] => Array
                                                                (
                                                                    [value] => s
                                                                    [label] => SI-prefix
                                                                )

                                                        )

                                                    [label] => X-Axis value type
                                                    [type] => select
                                                    [value] => auto
                                                    [name] => type
                                                )

                                            [cases] => Array
                                                (
                                                    [0] => Array
                                                        (
                                                            [value] => hide
                                                        )

                                                    [1] => Array
                                                        (
                                                            [value] => auto
                                                        )

                                                    [2] => Array
                                                        (
                                                            [value] => d
                                                        )

                                                    [3] => Array
                                                        (
                                                            [inputs] => Array
                                                                (
                                                                    [0] => Array
                                                                        (
                                                                            [help] => Select the tick format for the axis.
                                                                            [data] => Array
                                                                                (
                                                                                    [0] => Array
                                                                                        (
                                                                                            [value] => 5
                                                                                            [label] => 0.00001
                                                                                        )

                                                                                    [1] => Array
                                                                                        (
                                                                                            [value] => 4
                                                                                            [label] => 0.0001
                                                                                        )

                                                                                    [2] => Array
                                                                                        (
                                                                                            [value] => 3
                                                                                            [label] => 0.001
                                                                                        )

                                                                                    [3] => Array
                                                                                        (
                                                                                            [value] => 2
                                                                                            [label] => 0.01
                                                                                        )

                                                                                    [4] => Array
                                                                                        (
                                                                                            [value] => 1
                                                                                            [label] => 0.1
                                                                                        )

                                                                                    [5] => Array
                                                                                        (
                                                                                            [value] => 0
                                                                                            [label] => 1
                                                                                        )

                                                                                )

                                                                            [label] => Axis tick format
                                                                            [type] => select
                                                                            [value] => 1
                                                                            [name] => precision
                                                                        )

                                                                )

                                                            [value] => e
                                                        )

                                                    [4] => Array
                                                        (
                                                            [inputs] => Array
                                                                (
                                                                    [0] => Array
                                                                        (
                                                                            [help] => Select the tick format for the axis.
                                                                            [data] => Array
                                                                                (
                                                                                    [0] => Array
                                                                                        (
                                                                                            [value] => 5
                                                                                            [label] => 0.00001
                                                                                        )

                                                                                    [1] => Array
                                                                                        (
                                                                                            [value] => 4
                                                                                            [label] => 0.0001
                                                                                        )

                                                                                    [2] => Array
                                                                                        (
                                                                                            [value] => 3
                                                                                            [label] => 0.001
                                                                                        )

                                                                                    [3] => Array
                                                                                        (
                                                                                            [value] => 2
                                                                                            [label] => 0.01
                                                                                        )

                                                                                    [4] => Array
                                                                                        (
                                                                                            [value] => 1
                                                                                            [label] => 0.1
                                                                                        )

                                                                                    [5] => Array
                                                                                        (
                                                                                            [value] => 0
                                                                                            [label] => 1
                                                                                        )

                                                                                )

                                                                            [label] => Axis tick format
                                                                            [type] => select
                                                                            [value] => 1
                                                                            [name] => precision
                                                                        )

                                                                )

                                                            [value] => f
                                                        )

                                                    [5] => Array
                                                        (
                                                            [inputs] => Array
                                                                (
                                                                    [0] => Array
                                                                        (
                                                                            [help] => Select the tick format for the axis.
                                                                            [data] => Array
                                                                                (
                                                                                    [0] => Array
                                                                                        (
                                                                                            [value] => 5
                                                                                            [label] => 0.00001
                                                                                        )

                                                                                    [1] => Array
                                                                                        (
                                                                                            [value] => 4
                                                                                            [label] => 0.0001
                                                                                        )

                                                                                    [2] => Array
                                                                                        (
                                                                                            [value] => 3
                                                                                            [label] => 0.001
                                                                                        )

                                                                                    [3] => Array
                                                                                        (
                                                                                            [value] => 2
                                                                                            [label] => 0.01
                                                                                        )

                                                                                    [4] => Array
                                                                                        (
                                                                                            [value] => 1
                                                                                            [label] => 0.1
                                                                                        )

                                                                                    [5] => Array
                                                                                        (
                                                                                            [value] => 0
                                                                                            [label] => 1
                                                                                        )

                                                                                )

                                                                            [label] => Axis tick format
                                                                            [type] => select
                                                                            [value] => 1
                                                                            [name] => precision
                                                                        )

                                                                )

                                                            [value] => p
                                                        )

                                                    [6] => Array
                                                        (
                                                            [value] => s
                                                        )

                                                )

                                            [type] => conditional
                                            [name] => x_axis_type
                                        )

                                    [2] => Array
                                        (
                                            [help] => Provide a label for the axis.
                                            [placeholder] => Axis label
                                            [label] => Y-Axis label
                                            [type] => text
                                            [value] => Y-axis
                                            [name] => y_axis_label
                                        )

                                    [3] => Array
                                        (
                                            [test_param] => Array
                                                (
                                                    [help] => Select the value type of the axis.
                                                    [data] => Array
                                                        (
                                                            [0] => Array
                                                                (
                                                                    [value] => hide
                                                                    [label] => -- Do not show values --
                                                                )

                                                            [1] => Array
                                                                (
                                                                    [value] => auto
                                                                    [label] => Auto
                                                                )

                                                            [2] => Array
                                                                (
                                                                    [value] => d
                                                                    [label] => Integer
                                                                )

                                                            [3] => Array
                                                                (
                                                                    [value] => e
                                                                    [label] => Exponent
                                                                )

                                                            [4] => Array
                                                                (
                                                                    [value] => f
                                                                    [label] => Float
                                                                )

                                                            [5] => Array
                                                                (
                                                                    [value] => p
                                                                    [label] => Percent
                                                                )

                                                            [6] => Array
                                                                (
                                                                    [value] => s
                                                                    [label] => SI-prefix
                                                                )

                                                        )

                                                    [label] => Y-Axis value type
                                                    [type] => select
                                                    [value] => auto
                                                    [name] => type
                                                )

                                            [cases] => Array
                                                (
                                                    [0] => Array
                                                        (
                                                            [value] => hide
                                                        )

                                                    [1] => Array
                                                        (
                                                            [value] => auto
                                                        )

                                                    [2] => Array
                                                        (
                                                            [value] => d
                                                        )

                                                    [3] => Array
                                                        (
                                                            [inputs] => Array
                                                                (
                                                                    [0] => Array
                                                                        (
                                                                            [help] => Select the tick format for the axis.
                                                                            [data] => Array
                                                                                (
                                                                                    [0] => Array
                                                                                        (
                                                                                            [value] => 5
                                                                                            [label] => 0.00001
                                                                                        )

                                                                                    [1] => Array
                                                                                        (
                                                                                            [value] => 4
                                                                                            [label] => 0.0001
                                                                                        )

                                                                                    [2] => Array
                                                                                        (
                                                                                            [value] => 3
                                                                                            [label] => 0.001
                                                                                        )

                                                                                    [3] => Array
                                                                                        (
                                                                                            [value] => 2
                                                                                            [label] => 0.01
                                                                                        )

                                                                                    [4] => Array
                                                                                        (
                                                                                            [value] => 1
                                                                                            [label] => 0.1
                                                                                        )

                                                                                    [5] => Array
                                                                                        (
                                                                                            [value] => 0
                                                                                            [label] => 1
                                                                                        )

                                                                                )

                                                                            [label] => Axis tick format
                                                                            [type] => select
                                                                            [value] => 1
                                                                            [name] => precision
                                                                        )

                                                                )

                                                            [value] => e
                                                        )

                                                    [4] => Array
                                                        (
                                                            [inputs] => Array
                                                                (
                                                                    [0] => Array
                                                                        (
                                                                            [help] => Select the tick format for the axis.
                                                                            [data] => Array
                                                                                (
                                                                                    [0] => Array
                                                                                        (
                                                                                            [value] => 5
                                                                                            [label] => 0.00001
                                                                                        )

                                                                                    [1] => Array
                                                                                        (
                                                                                            [value] => 4
                                                                                            [label] => 0.0001
                                                                                        )

                                                                                    [2] => Array
                                                                                        (
                                                                                            [value] => 3
                                                                                            [label] => 0.001
                                                                                        )

                                                                                    [3] => Array
                                                                                        (
                                                                                            [value] => 2
                                                                                            [label] => 0.01
                                                                                        )

                                                                                    [4] => Array
                                                                                        (
                                                                                            [value] => 1
                                                                                            [label] => 0.1
                                                                                        )

                                                                                    [5] => Array
                                                                                        (
                                                                                            [value] => 0
                                                                                            [label] => 1
                                                                                        )

                                                                                )

                                                                            [label] => Axis tick format
                                                                            [type] => select
                                                                            [value] => 1
                                                                            [name] => precision
                                                                        )

                                                                )

                                                            [value] => f
                                                        )

                                                    [5] => Array
                                                        (
                                                            [inputs] => Array
                                                                (
                                                                    [0] => Array
                                                                        (
                                                                            [help] => Select the tick format for the axis.
                                                                            [data] => Array
                                                                                (
                                                                                    [0] => Array
                                                                                        (
                                                                                            [value] => 5
                                                                                            [label] => 0.00001
                                                                                        )

                                                                                    [1] => Array
                                                                                        (
                                                                                            [value] => 4
                                                                                            [label] => 0.0001
                                                                                        )

                                                                                    [2] => Array
                                                                                        (
                                                                                            [value] => 3
                                                                                            [label] => 0.001
                                                                                        )

                                                                                    [3] => Array
                                                                                        (
                                                                                            [value] => 2
                                                                                            [label] => 0.01
                                                                                        )

                                                                                    [4] => Array
                                                                                        (
                                                                                            [value] => 1
                                                                                            [label] => 0.1
                                                                                        )

                                                                                    [5] => Array
                                                                                        (
                                                                                            [value] => 0
                                                                                            [label] => 1
                                                                                        )

                                                                                )

                                                                            [label] => Axis tick format
                                                                            [type] => select
                                                                            [value] => 1
                                                                            [name] => precision
                                                                        )

                                                                )

                                                            [value] => p
                                                        )

                                                    [6] => Array
                                                        (
                                                            [value] => s
                                                        )

                                                )

                                            [type] => conditional
                                            [name] => y_axis_type
                                        )

                                    [4] => Array
                                        (
                                            [type] => boolean
                                            [help] => Would you like to add a legend?
                                            [name] => show_legend
                                            [value] => true
                                            [label] => Show legend
                                        )

                                )

                            [html] => Bar Horizontal (NVD3)
                        )

                    [1] => Array
                        (
                            [description] => Renders a stacked horizontal bar diagram using NVD3 hosted at http://www.nvd3.org.
                            [embeddable] => 
                            [href] => /galaxy/plugins/visualizations/nvd3_horizontal_stacked/show
                            [entry_point] => Array
                                (
                                    [type] => chart
                                    [attr] => Array
                                        (
                                            [load] => nvd3_horizontal_stacked
                                            [src] => ../../nvd3_bar/static/nvd3.js
                                            [css] => ../../nvd3_bar/static/nvd3.css
                                        )

                                    [file] => 
                                )

                            [groups] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => color
                                            [name] => color
                                            [label] => Pick a series color
                                        )

                                    [1] => Array
                                        (
                                            [is_label] => true
                                            [type] => data_column
                                            [name] => tooltip
                                            [is_auto] => true
                                            [label] => Data point labels
                                        )

                                    [2] => Array
                                        (
                                            [placeholder] => Data label
                                            [type] => text
                                            [name] => key
                                            [value] => Data label
                                            [label] => Provide a label
                                        )

                                    [3] => Array
                                        (
                                            [is_label] => true
                                            [type] => data_column
                                            [name] => x
                                            [is_auto] => true
                                            [label] => Values for x-axis
                                        )

                                    [4] => Array
                                        (
                                            [is_numeric] => true
                                            [type] => data_column
                                            [name] => y
                                            [label] => Values for y-axis
                                        )

                                )

                            [logo] => ./static/plugins/visualizations/nvd3/nvd3_horizontal_stacked/static/logo.png
                            [specs] => Array
                                (
                                    [exports] => Array
                                        (
                                            [0] => png
                                            [1] => svg
                                            [2] => pdf
                                        )

                                    [tag] => svg
                                    [use_panels] => no
                                )

                            [target] => galaxy_main
                            [name] => nvd3_horizontal_stacked
                            [title] => 
                            [settings] => Array
                                (
                                    [0] => Array
                                        (
                                            [help] => Provide a label for the axis.
                                            [placeholder] => Axis label
                                            [label] => X-Axis label
                                            [type] => text
                                            [value] => X-axis
                                            [name] => x_axis_label
                                        )

                                    [1] => Array
                                        (
                                            [test_param] => Array
                                                (
                                                    [help] => Select the value type of the axis.
                                                    [data] => Array
                                                        (
                                                            [0] => Array
                                                                (
                                                                    [value] => hide
                                                                    [label] => -- Do not show values --
                                                                )

                                                            [1] => Array
                                                                (
                                                                    [value] => auto
                                                                    [label] => Auto
                                                                )

                                                            [2] => Array
                                                                (
                                                                    [value] => d
                                                                    [label] => Integer
                                                                )

                                                            [3] => Array
                                                                (
                                                                    [value] => e
                                                                    [label] => Exponent
                                                                )

                                                            [4] => Array
                                                                (
                                                                    [value] => f
                                                                    [label] => Float
                                                                )

                                                            [5] => Array
                                                                (
                                                                    [value] => p
                                                                    [label] => Percent
                                                                )

                                                            [6] => Array
                                                                (
                                                                    [value] => s
                                                                    [label] => SI-prefix
                                                                )

                                                        )

                                                    [label] => X-Axis value type
                                                    [type] => select
                                                    [value] => auto
                                                    [name] => type
                                                )

                                            [cases] => Array
                                                (
                                                    [0] => Array
                                                        (
                                                            [value] => hide
                                                        )

                                                    [1] => Array
                                                        (
                                                            [value] => auto
                                                        )

                                                    [2] => Array
                                                        (
                                                            [value] => d
                                                        )

                                                    [3] => Array
                                                        (
                                                            [inputs] => Array
                                                                (
                                                                    [0] => Array
                                                                        (
                                                                            [help] => Select the tick format for the axis.
                                                                            [data] => Array
                                                                                (
                                                                                    [0] => Array
                                                                                        (
                                                                                            [value] => 5
                                                                                            [label] => 0.00001
                                                                                        )

                                                                                    [1] => Array
                                                                                        (
                                                                                            [value] => 4
                                                                                            [label] => 0.0001
                                                                                        )

                                                                                    [2] => Array
                                                                                        (
                                                                                            [value] => 3
                                                                                            [label] => 0.001
                                                                                        )

                                                                                    [3] => Array
                                                                                        (
                                                                                            [value] => 2
                                                                                            [label] => 0.01
                                                                                        )

                                                                                    [4] => Array
                                                                                        (
                                                                                            [value] => 1
                                                                                            [label] => 0.1
                                                                                        )

                                                                                    [5] => Array
                                                                                        (
                                                                                            [value] => 0
                                                                                            [label] => 1
                                                                                        )

                                                                                )

                                                                            [label] => Axis tick format
                                                                            [type] => select
                                                                            [value] => 1
                                                                            [name] => precision
                                                                        )

                                                                )

                                                            [value] => e
                                                        )

                                                    [4] => Array
                                                        (
                                                            [inputs] => Array
                                                                (
                                                                    [0] => Array
                                                                        (
                                                                            [help] => Select the tick format for the axis.
                                                                            [data] => Array
                                                                                (
                                                                                    [0] => Array
                                                                                        (
                                                                                            [value] => 5
                                                                                            [label] => 0.00001
                                                                                        )

                                                                                    [1] => Array
                                                                                        (
                                                                                            [value] => 4
                                                                                            [label] => 0.0001
                                                                                        )

                                                                                    [2] => Array
                                                                                        (
                                                                                            [value] => 3
                                                                                            [label] => 0.001
                                                                                        )

                                                                                    [3] => Array
                                                                                        (
                                                                                            [value] => 2
                                                                                            [label] => 0.01
                                                                                        )

                                                                                    [4] => Array
                                                                                        (
                                                                                            [value] => 1
                                                                                            [label] => 0.1
                                                                                        )

                                                                                    [5] => Array
                                                                                        (
                                                                                            [value] => 0
                                                                                            [label] => 1
                                                                                        )

                                                                                )

                                                                            [label] => Axis tick format
                                                                            [type] => select
                                                                            [value] => 1
                                                                            [name] => precision
                                                                        )

                                                                )

                                                            [value] => f
                                                        )

                                                    [5] => Array
                                                        (
                                                            [inputs] => Array
                                                                (
                                                                    [0] => Array
                                                                        (
                                                                            [help] => Select the tick format for the axis.

**Comment by shawnawsu** [comment]
Are you using the `tripal_galaxy_get_proxy_url` ?

**Comment by NicHerndon** [comment]
No. I’m using

  $submission = tripal_galaxy_get_submission(113);
  $datasets = tripal_galaxy_get_datasets($submission);

**Comment by shawnawsu** [comment]
I think option 2 from the docs is what you're looking for.

Option 2: Providing Download Links for Users
Once the workflow has completed you may want to provide links for the end-user to view or download results from the workflow. As opposed to option #1, this does not result in files being downloaded to the Drupal server and will not affect the user’s file quota. To create a link for either viewing or downloading you should use the tripal_galaxy_get_proxy_url. This function returns a URL you can use in your application for viewing or downloading. For example, the following retrieves a URL for downloading a dataset:

```
global $user;

// Get the dataset.
$dataset = tripal_galaxy_get_dataset($submission, $dataset_id);

// Now get the Proxy URL and create the link.
$proxy_url = tripal_galaxy_get_proxy_url($submission, $dataset, $uid, 'download');
$link = l($dataset['name'], $proxy_url) . ' (' . $dataset[file_size] . ')';
```
The $link variable now contains an HTML formatted link for downloading the file. It also lists the file size next to the link. You can use this variable anywhere that you create content for a page in your application. Notice that the last argument to the tripal_galaxy_get_proxy_url() function is the string download. This is the action that the proxy URL should perform.

Similarly to retrieve a URL for viewing the dataset:

```
global $user;

// Get the dataset.
$dataset = tripal_galaxy_get_dataset($submission, $dataset_id);

// Any files that are smaller than 1MB can be shown in a browser.
if ($dataset['file_size'] < pow(10, 6)) {
  $proxy_url = tripal_galaxy_get_proxy_url($submission, $dataset, $uid, 'viewer');
  $link =  l($dataset['name'], $proxy_url);
}
else {
  $link =  'Result file is too large to view. Please download.';
}
```
Note in the call to tripal_galaxy_get_proxy_url the last argument is viewer. With this action, when the link is clicked the file will be shown on a results page provided by the Tripal Galaxy module. The page displays results in an HTML IFrame. If you prefer to show results in a stand-alone page use viewer-full as the last argument.

**Comment by NicHerndon** [comment]
Thank you. I’ll give this a try and keep you posted.

**Comment by NicHerndon** [comment]
Does this work if the workflow generates multiple files?

**Comment by NicHerndon** [comment]
How do I get the $dataset_id?

**Comment by spficklin** [comment]
Hi Nic, I think you can find what you need in the online docs.  

You can get the list of datasets using the ` tripal_galaxy_get_datasets` function.  You can see code examples here:  https://tripal-galaxy.readthedocs.io/en/latest/API/api_overview.html#retrieving-a-dataset

**Comment by NicHerndon** [comment]
Well, we came full circle: this is the API call ($datasets = tripal_galaxy_get_datasets($submission);) that returns over 26K lines.

**Comment by spficklin** [comment]
It should have all of the data you need to create the links.  You need to iterate through the elements of the `$datasets` array and find the file you want to create a download link for. 

For example:
```
$dataset = NULL;
$datasets = tripal_galaxy_get_datasets($submission);
foreach ($datasets as $ds) {
  if ($ds['name'] == 'WGCNA: eigengene visualization') {
    $dataset = $ds;
  }
}

// Now get the Proxy URL and create the link.
$proxy_url = tripal_galaxy_get_proxy_url($submission, $dataset, $uid, 'download');
$link = l($dataset['name'], $proxy_url) . ' (' . $dataset[file_size] . ')';
```

**Comment by spficklin** [comment]
Nic, just checking if you got this worked out?

**Comment by NicHerndon** [comment]
Thank you for checking on this.

This is still an open issue. I opened this ticket because the structure returned by tripal_galaxy_get_datasets seems to contain too much information. In the thread, I was told to use tripal_galaxy_get_datasets to get the $dataset_id, to get the links for the user. I would like to see why tripal_galaxy_get_datasets returns so much data.

**Comment by spficklin** [comment]
Hi Nic.

It returns all of the details about a dataset on the Galaxy server.  We just pass it through. it's not something that Tripal Galaxy module creates.   There is a lot of information in there, that's true, but it should help you identify the dataset_id you need to use.   Unless you are having performance problems with a huge number of datasets in one history I don't see that this would be problematic.  Do you have a huge number of datasets in one history?

**Comment by NicHerndon** [comment]
I was able to create the links to the datasets with the code snippet you provided. Thank you.

**Comment by spficklin** [comment]
Great!  glad you got it working.
