### ISSUE TITLE
Missing value in function return: tripal_galaxy_get_active_submissions

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal_galaxy#145]
### System Information
- Tripal Version: 7.x-3.0
- Drupal Version: 7.66
- Latest Commit: https://github.com/tripal/tripal_galaxy/commit/36f2cf84ef61874cff13ad2c202aab28dadc633c 

### Issue Description
Using drush command 
`drush trp-galaxy-status --uri=https://site.com/ --root=/var/www/drupal` 
fails when not given a submission ID, as specified [by the documentation](https://tripal-galaxy.readthedocs.io/en/latest/automating_tasks.html#automatic-job-status-checking) for use with a cron configuration.

`tripal_galaxy_get_active_submissions` does not collect any `errors` data, i.e. `$submission->errors`, [which is expected later](https://github.com/tripal/tripal_galaxy/blob/36f2cf84ef61874cff13ad2c202aab28dadc633c/api/tripal_galaxy.api.inc#L554). Since there is no data, the variable is null, which causes the error: 
```
TypeError: Argument 2 passed to tripal_galaxy_get_history() must be of the type string, null given, 
called in /var/www/drupal/sites/all/modules/tripal_galaxy/api/tripal_galaxy.api.inc
on line 555 in tripal_galaxy_get_history() (line 1014 of /var/www/drupal/sites/all/modules/tripal_galaxy/api/tripal_galaxy.api.inc)
``` 
A similar function that gets called when submission ID **is** provided (`tripal_galaxy_get_submission($sid)`) does return an `errors` value.
### Steps to reproduce:
Call the command: `drush trp-galaxy-status --uri=https://site.com/ --root=/var/www/drupal` without specifying the submission ID (sid); `--submission=72`

<hr>
This may be a contributing factor to #141

**Comment by spficklin** [comment]
This should be fixed with PR #144. Please comment if the problem persists.
