### ISSUE TITLE
Unable to add workflow

### ISSUE THREAD

**Issue by heh30** [tripal/tripal_galaxy#148]
When adding a workflow I encounter the following error:

> Error building tool: toolshed.g2.bx.psu.edu/repos/devteam/bwa/bwa/0.7.17.4. Galaxy Server response: Could not find tool with id 'toolshed.g2.bx.psu.edu%2Frepos%2Fdevteam%2Fbwa%2Fbwa%2F0.7.17.4'.
> Could not create workflow

This error is encountered regardless of the galaxy instance used; my own or the usegalaxy.org instance.

The message generated within galaxy is:

> [30/Sep/2019:08:43:26 -0700] "GET /api/tools/toolshed.g2.bx.psu.edu%252Frepos%252Fdevteam%252Fbwa%252Fbwa%252F0.7.17.4/build/?key=de1b09186b2ca68994d58f181b15e007&history_id=1cd8e2f6b131e891 HTTP/1.1" 404 - "-" "-"

I believe the data being passed into galaxy is having the '/' replaced with '%252F' which is causing it to fail.  When I navigate to my.galaxy.instance//api/tools/toolshed.g2.bx.psu.edu%252Frepos%252Fdevteam%252Fbwa%252Fbwa%252F0.7.17.4/build/?key=de1b09186b2ca68994d58f181b15e007&history_id=1cd8e2f6b131e891 I encounter the error, but when I replace it with my.galaxy.instance//api/tools/toolshed.g2.bx.psu.edu/repos/devteam/bwa/bwa/0.7.17.4/build/?key=de1b09186b2ca68994d58f181b15e007&history_id=1cd8e2f6b131e891 the page with tool details is displayed.  

Galaxy 19.05
Drupal 7.67
Tripal 7.x-3.2
Tripal Galaxy 7.x-1.0
Webform 7.x-4.20

I was able to successfully add a workflow after adjusting an apache configuration setting, AllowEncodedSlashes = on which is different that specified with in the Galaxy proxy configuration documentation with indicates this value should be set to NoDecode.

**Comment by spficklin** [comment]
@bcuser30 can you send me a copy of the workflow you are trying to use so I can test it?

**Comment by heh30** [comment]
With my own galaxy instance, this is still a problem (if I don't have the workaround enabled).

I'm able to successfully import workflows on the usegalaxy.org instance.  Unfortunately, I have no way of knowing how their apache settings are configured.

**Comment by spficklin** [comment]
Perhaps some of the Galaxy guru's can help with the admin settings?  There is a Gitter channel you can ask questions:  https://gitter.im/galaxyproject/Lobby.

As you think this is an admin setting issue for Galaxy I'm going to close this out. But if you think otherwise later please comment and we can reopen it.
