### ISSUE TITLE
Workflow status not updated properly when workflow is changed on galaxy side

### ISSUE THREAD

**Issue by cwytko** [tripal/tripal_galaxy#15]

**Comment by cwytko** [comment]
Found this issue while checking the workflow tables on a join for the file_usage column of the table for users to see what files they have uploaded and where they are being used (if at all)

**Comment by spficklin** [comment]
It's not clear what this issue is.  Can you give more details?

**Comment by spficklin** [comment]
I think this is duplicate of issue #24 .  Marking closed unless you can provide further details.
