### ISSUE TITLE
tripal_galaxy_get_proxy_url() seems to retrieve different datasets.

### ISSUE THREAD

**Issue by NicHerndon** [tripal/tripal_galaxy#152]
The datasets retrieved with `tripal_galaxy_get_proxy_url()` are
06-TOM_heatmap_block_1 (358026)
06-cluster_dendrogram_block_1 (244738)
network_construction_report.pdf (0)
filtered_GEM.csv (3616823)
gene_module_file.csv (100324)
network_edges.txt (1009664)
module_association_report.pdf (0)

whereas the datasets retrieved with `https://tgwebdev.cam.uchc.edu/admin/tripal/extension/galaxy/job-queue` are
20191221_113022_11_PARAMS.TSV
20191221_113022_11_ENV_DATA.TSV
20191221_113022_11_DNA_DATA.TSV
SAMΒADA ON DATA 3, DATA 2, AND DATA 1
SAMΒADA ON DATA 3, DATA 2, AND DATA 1
SAMΒADA ON DATA 3, DATA 2, AND DATA 1
SAMΒADA ON DATA 3, DATA 2, AND DATA 1

**Comment by spficklin** [comment]
This has been fixed  in person at the Tripal Codefest.
