### ISSUE TITLE
Images retrieved from Galaxy server are malformed

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal_galaxy#160]
Images created by a workflow on Galaxy get returned to Tripal Galaxy but they are not able to open. Currently seeing broken PNG files, testing other image types.

Files appear to be correct in Galaxy history, and also appear to be correct when transferring to Tripal Galaxy (correct size, correct type).

Example .png attached
![Galaxy14- 01-sample_dendrogram -1](https://user-images.githubusercontent.com/9593623/80219695-d63ad500-8610-11ea-8b80-7e0839026a54.png)

**Comment by almasaeed2010** [comment]
Looks like there are 4 spaces prepended to the file when being streamed by Galaxy or when being saved by Tripal_Galaxy. In either case, we can fix it by trimming the content of the file `trim(file_get_contents('file_path'))`.

You can inspect the image using `xxd filenam.png | less`
<img width="713" alt="Screen Shot 2020-04-24 at 12 34 01 PM" src="https://user-images.githubusercontent.com/1512664/80236080-a13a7c80-8628-11ea-945c-6d9710f4793b.png">

Once the spaces are removed, the image will render correctly:
![80219695-d63ad500-8610-11ea-8b80-7e0839026a54](https://user-images.githubusercontent.com/1512664/80236144-bd3e1e00-8628-11ea-8975-794e13ad4852.png)

**Comment by Ferrisx4** [comment]
Issue appears to be related to the Tripal Sequence Similarity Search module putting four extra spaces on every page. Disabling that module removes the four extra spaces from every page.

Closing for now.

**Comment by Ferrisx4** [comment]
This has been fixed by https://github.com/tripal/tripal_sequence_similarity_search/issues/8
