### ISSUE TITLE
Hard coded file types in file uploader/selector

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal_galaxy#18]
The supported file types on file selector components coming from a Galaxy workflow are hardcoded on line 584 and 589 of the includes/tripal_galaxy.webform.inc file.  These need to come directly from the Galaxy workflow.

**Comment by cwytko** [comment]
This is fixed now, there is only one bug that I would need to double check, I need to make sure if that tool has multiple input file types that the right uploading step is associated to the right input type of the tool

**Comment by cwytko** [comment]
The file extension is not being enforced @spficklin How do I enforce it using the html5 component?

**Comment by spficklin** [comment]
Fixes have been made to the Javascript to validate the extension type.
