### ISSUE TITLE
missing options at some steps from a workflow

### ISSUE THREAD

**Issue by MingChen0919** [tripal/tripal_galaxy#20]
Some options are missing from a workflow, see the comparison between workflow from Tripal and workflow from Galaxy:

<img width="963" alt="screen shot 2017-09-11 at 11 05 25 pm" src="https://user-images.githubusercontent.com/1262709/30306519-a87eaac6-9746-11e7-8769-4fa9173d7d67.png">
<img width="733" alt="screen shot 2017-09-11 at 11 05 34 pm" src="https://user-images.githubusercontent.com/1262709/30306522-aaba89d6-9746-11e7-8365-30cb2f413761.png">

**Comment by spficklin** [comment]
This was been fixed and those options now appear.  Can you test and let me know if you still have issues?

**Comment by MingChen0919** [comment]
sure. I am testing it right now.

**Comment by MingChen0919** [comment]
yes, it's fixed. thanks. I'll close this issue.
