### ISSUE TITLE
List collection issue: "Cannot load invalid dataset identifier - missing name" error

### ISSUE THREAD

**Issue by MingChen0919** [tripal/tripal_galaxy#22]
The tested workflow has a List collection input: https://galaxy.bioinfo.wsu.edu/u/mingchen0919/w/quality-control-se-dataset-collection

Files were successfully uploaded to Galaxy server after running the `drush trp-galaxy-invoke` command. Then it generated this error:

<img width="1254" alt="screen shot 2017-09-11 at 11 16 28 pm" src="https://user-images.githubusercontent.com/1262709/30306743-ffc05d06-9747-11e7-859e-e6b702815949.png">

**Comment by cwytko** [comment]
@MingChen0919 Is this error still showing up in your workflow invocations?

**Comment by MingChen0919** [comment]
@cwytko, I just tested with the latest version.  This error didn't show up, but it gave a new error. Last time the files uploaded to Galaxy successfully. This time the files failed to upload.

<img width="961" alt="screen shot 2017-09-20 at 8 53 02 pm" src="https://user-images.githubusercontent.com/1262709/30674126-e3efa492-9e45-11e7-9c5a-7e240d0a2f5e.png">

**Comment by spficklin** [comment]
I just committed a fix for this.  Can you try again and let me know?  You'll have to delete the workflow from Tripal and readd it before testing.

**Comment by MingChen0919** [comment]
@spficklin I tested this several times on both Tripal 2 and 3, it didn't work for me. I still got the same error. Every time I cloned the tripal galaxy module to make sure I got the newest version of the module.

**Comment by spficklin** [comment]
Looks like this was a problem with blend4php which has been fixed.
