### ISSUE TITLE
support fastq file with extension `.fq`.

### ISSUE THREAD

**Issue by MingChen0919** [tripal/tripal_galaxy#23]
A lot of fastq files have extension `.fq`. It would be good to make `.fq` a supported fastq file extension.

**Comment by spficklin** [comment]
Hi @MingChen0919.  The allowed file types are specified in the workflow.  The module just pulls those that are set in the workflow and then enforce them.  If you'd like a .fq extension to be allowed then just you need to set it in the workflow.

**Comment by MingChen0919** [comment]
Workflow doesn't allow to specify file types, but I just realized that in Galaxy, the uploaded `.fq` files were automatically converted into `fastq` files. So I am closing this issue. Thanks!

**Comment by spficklin** [comment]
Oh, but our Tripal uploader may not like the .fq extension if it's not specified in the workflow.  I thought you could change the allowed extensions for a tool.  You're not able to do that?

**Comment by MingChen0919** [comment]
End users can't specify allowed extensions. The allowed file types are specified in the source code by tool developers, not by tool users.

**Comment by spficklin** [comment]
Just to clarify, a workflow developer (not an end-user) cannot adjust the allowed file types for a tool?

**Comment by MingChen0919** [comment]
that's right. A workflow developer cannot adjust the allowed file types for a tool.

**Comment by spficklin** [comment]
I added a quick fix to make this work.  Anytime a default 'fastq' file is specified it will also allow a 'fq' extension as well.
