### ISSUE TITLE
label-value mismatch issue for boolean input fields.

### ISSUE THREAD

**Issue by MingChen0919** [tripal/tripal_galaxy#25]
Usually for a boolean field for a tool, The label true (yes) is mapped to true (yes) and the label false (no) is mapped to false (no). However, this is not necessary for Galaxy tools. For example, the tool below has two boolean inputs, for the first one, the 'truevalue' is mapped to 'fastq' while the 'falsevalue' is mapped to 'fasta'. It seems that The tripal galaxy module assumes that for a boolean input, if I select "Yes", it will pass the value "Yes". This can cause problems in many tools. 

<img width="737" alt="screen shot 2017-09-28 at 8 21 05 pm" src="https://user-images.githubusercontent.com/1262709/30996027-af23c4cc-a48b-11e7-9a91-f4755460957a.png">

**Comment by MingChen0919** [comment]
I figured out that I can change the values to whatever I want by editing the webform components. Can the boolean input values be obtained programmatically? If not, I think it would be good to mention this in the module's documentation.

**Comment by spficklin** [comment]
Hmmm.... boolean to mean means "true" and "false" or 0 and 1.  So, I think this is a bit of a stretch on the data type. But, we can adjust our code to deal with it.  We'll work on it.  Thanks for noticing this.

**Comment by spficklin** [comment]
Can you point us to a workflow that uses boolean in this way?

**Comment by MingChen0919** [comment]
workflow `sra-tool-rna-alignment-pe`: https://galaxy.bioinfo.wsu.edu/u/mingchen0919/w/sra-tool-rna-alignment-pe

**Comment by cwytko** [comment]
This should be fixed @MingChen0919 please confirm when you have time!

**Comment by cwytko** [comment]
I'll wait for confirmation **before** closing

**Comment by MingChen0919** [comment]
confirmed. thanks:)
