### ISSUE TITLE
tripal data collection problem

### ISSUE THREAD

**Issue by mestato** [tripal/tripal_galaxy#28]
I am using the most up to date code for tripal and galaxy module. I created a WGCNA workflow and submitted to galaxy.  When I run a status check with `drush trp-galaxy-status --submission=1` this is the error:
`Updating status of workflow...
exception 'ErrorException' with message 'API error. The following parameters for function GalaxyDatasets::show() are required: dataset_id.' in     [error]
/var/www/html/sites/all/modules/tripal-extensions/tripal_galaxy/api/tripal_galaxy.api.inc:180
Stack trace:
#0 /var/www/html/sites/all/modules/tripal-extensions/tripal_galaxy/tripal_galaxy.drush.inc(78): tripal_galaxy_check_submission_status('1')
#1 [internal function]: drush_tripal_galaxy_trp_galaxy_status()
#2 phar:///usr/local/bin/drush/includes/command.inc(422): call_user_func_array('drush_tripal_ga...', Array)
#3 phar:///usr/local/bin/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#4 [internal function]: drush_command()
#5 phar:///usr/local/bin/drush/includes/command.inc(199): call_user_func_array('drush_command', Array)
#6 phar:///usr/local/bin/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#7 phar:///usr/local/bin/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#8 phar:///usr/local/bin/drush/includes/startup.inc(458): drush_main()
#9 phar:///usr/local/bin/drush/includes/startup.inc(365): drush_run_main(false, '/', 'Phar detected. ...')
#10 phar:///usr/local/bin/drush/drush(114): drush_startup(Array)
#11 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#12 {main}`

**Comment by spficklin** [comment]
Are you using the most up-to-date blend4php?

**Comment by mestato** [comment]
Yes, blend4php is up to date, cloned from master branch. I only get this error when the workflow fails on galaxy with an error. If the workflow completes, it works fine.

**Comment by spficklin** [comment]
Ah... okay.   When the workflow fails on Galaxy what kind of failure is it?

**Comment by mestato** [comment]
I can produce it by using the WGCNA workflow on WSU (shared workflow entitled "wgcna-analysis") with incorrect input files. From the galaxy side, I can see that It fails at step 5: WGCNA construct network with the error:
```
Fatal error: An undefined error occured, please check your intput carefully and contact your administrator.
Loading required package: dynamicTreeCut
Loading required package: fastcluster

Attaching package: 'fastcluster'

The following object is masked from 'package:stats':

    hclust



Attaching package: 'WGCNA'

The following object is masked from 'package:stats':

    cor



processing file: wgcna_construct_network.Rmd
Quitting from lines 47-50 (wgcna_construct_network.Rmd) 
Error in hclust(dist(expression_data), method = "average") : 
  N must be at least 2.
Calls: render ... withCallingHandlers -> withVisible -> eval -> eval -> hclust -> .Call
```

**Comment by mestato** [comment]
I was able to generate this error with a different workflow (hisat2-alignment-pe-dataset-collection ) by uploading a misformed fastq file. The error on the galaxy side was 
```
There was an error reading your input file. Your input file is likely malformed.
It is suggested that you double-check your original input file for errors -- helpful information for this purpose has been provided below.
```
The error on the Tripal side from drush trp-galaxy-status remained the same.

**Comment by spficklin** [comment]
I just pushed a fix that should resolve this problem for you.  It also fixes the problem if you try to check the status before the job finishes then the job report page is wonky.   Now, if you run the status check before the job finishes it will update the results for those steps that finished and inform the user that the other's are still running.   This required a change in the way we cache history contents, so you'll have to update the status of any already completed workflows.  Let me know if this fixes the problem for you and if so we can close out the issue.

**Comment by spficklin** [comment]
Hi @mestato and @MingChen0919 before closing this can you verify that all is good?  Thanks.

**Comment by MingChen0919** [comment]
confirmed. this issue can be closed.
