### ISSUE TITLE
Use Galaxy Data Libraries?

### ISSUE THREAD

**Issue by mestato** [tripal/tripal_galaxy#31]
Problem: In regards to the shared files for galaxy - where a tripal admin can make a file available for any user. As currently implemented, for example, if I make available the chestnut genome for analysis as a file, every time a user uses it in a workflow, it will be transferred to the galaxy server and stored in a new history. I may be wrong, but I think this results in the same file being repeatedly uploaded and stored on the galaxy server in many histories. 

Possible solution: [Galaxy data libraries](https://galaxyproject.org/data-libraries/) could offer a way for us to store globally accessible files on the galaxy side without storing them in multiple histories.

**Comment by cwytko** [comment]
One of the issues with this is that a tripal site wide file is being added multiple times on the galaxy side

**Comment by MingChen0919** [comment]
we can add often used reference genomes as built-in datasets to the WSU galaxy (see https://galaxyproject.org/admin/data-preparation/).  We can expose only files that already exist in the Galaxy history and Galaxy's built-in datasets to workflows.

**Comment by mestato** [comment]
We need to think about user interface. Its getting a bit cluttered - users can upload their own file directly, choose a file they've already uploaded, select a site wide file, or select a data collection. Would Galaxy history and Galaxy built-in datasets replace some of these (e.g. no more site wide file or already uploaded by user options), or would these options be added to the list? We need to make this intuitive.

**Comment by MingChen0919** [comment]
if workflows use datasets directly from galaxy, then I don't think we will need the site-wide file option and the already uploaded files option. Tripal won't store users data, but only display what data is available to them from Galaxy. Also, we probably won't need quota settings on Tripal site.

maybe I am wrong, perhaps we still need quota admin settings. Because all tripal submitted workflows are currently being executed by one single galaxy admin user.

**Comment by spficklin** [comment]
I removed this as a release-blocker and a milestone because unfortunately Galaxy does not support libraries of files that are not created by the Galaxy admin.    @cwytko make some progress asking for this ability with the Galaxy developers but we need to follow up.

**Comment by spficklin** [comment]
Should we close this out or have we accepted the reality that we can't really do what we want.
