### ISSUE TITLE
Error at trp-run-jobs never updates workflow status

### ISSUE THREAD

**Issue by mestato** [tripal/tripal_galaxy#32]
Occasionally, I will submit a workflow and drush trp-run-jobs will return an error such as:
```
Job execution failed: Cannot upload a file with an fid
```
(If I can figure out exactly how I manage to get that error, I'll file another issue). But if any error occurs at this job submission step, the workflow is left in a "Waiting" state for the user forever. Would be more helpful to update the workflow status to "error".

**Comment by spficklin** [comment]
So, that message should read "Cannot upload a file **_without_** an fid".  Looking at the code it seems this can only happen with a list of files or list of paired files.  I suspect for some reason the data list has an empty value in it.  I added some if statements to ignore empty fids and catch this, but this may not be the appropriate fix.  I pushed that change.   Let us know if you see this again.

**Comment by spficklin** [comment]
Before I close this out would you @mestato or @MingChen0919 check this one?

**Comment by MingChen0919** [comment]
I tried to test with a workflow that I knew would fail. I was unable to generate the same error (i.e., i didn't get the error message `Job execution failed: Cannot upload a file with an fid`). After i ran `drush trp-galaxy-status`,  the status on the tripal site is 'error', and the command line stdout is:

```
Updating status of workflow...
Job Failed.
No recipient addresses found in header
Done.
```

I guess that's what we expect to see?
