### ISSUE TITLE
history_content['content_link'] issue

### ISSUE THREAD

**Issue by MingChen0919** [tripal/tripal_galaxy#33]
I got this error when I ran the bdss-hisat2-alignment workflow.
![screen shot 2017-10-27 at 9 59 14 am](https://user-images.githubusercontent.com/1262709/32107802-b04f0e00-bafd-11e7-834a-3c702207e5c3.png)
I have submitted a [PR](https://github.com/tripal/tripal_galaxy/pull/30) to fix this issue.

**Comment by spficklin** [comment]
The pull request had merge conflicts so it was just easier to copy your fixes into the code.  So, effectively your PR fix has been applied.  Can you test and confirm all is good.

**Comment by MingChen0919** [comment]
confirmed. thanks!
