### ISSUE TITLE
missing chunks error when uploading big files (~5G)

### ISSUE THREAD

**Issue by MingChen0919** [tripal/tripal_galaxy#34]
When uploading big files (~5G), I occasionally got this error:

<img width="501" alt="screen shot 2017-12-05 at 2 45 33 pm" src="https://user-images.githubusercontent.com/1262709/33700082-fb4541fc-dae4-11e7-8eba-5132d121672a.png">

**Comment by cwytko** [comment]
@spficklin and I talked about this the other day, this involves no error checking on the tripal file upload js code

**Comment by cwytko** [comment]
@spficklin 

https://galaxyproject.org/support/loading-data/#get-data-upload

Apparently when we use their tool it's expected that the data set is at most 2G, anything larger and galaxy recommends using their FTP tool

I stumbled on this while going through the data library spec

**Comment by mestato** [comment]
Could Tripal detect the problem and try to use ftp for larger files? It sounds like the Tripal server would have to have a basic ftp software install (usual for linux distros) but not be an ftp server itself. 

Its less feasible to let users choose -since we offer workflows instead of individual tools, if we wanted to give the users upload options (ftp, http, URL), we have to recreate each workflow with 3 versions, one for each upload method. 

As a temporary fix, on the Tripal side we could check file size and only upload files less than 2Gb.

**Comment by mestato** [comment]
Actually, my comment might not be relevant. Is this an error on the user to Tripal upload or on the Tripal to Galaxy upload? @MingChen0919 ?

**Comment by MingChen0919** [comment]
@mestato it has problems on both sides. Galaxy has a 2G limit which makes Tripal to Galaxy upload a problem. Also, uploading big data to Tripal is not stable, which makes the user to Tripal upload an issue. I think a long term solution for this would be separating file uploading from workflows. That is, having some tools for users to upload data to Tripal and then transfer the data to Galaxy. Each user has a 'dataset library' to track uploaded files. Workflows select data from the `dataset library`. This is also the Galaxy style. You import data first, then you run jobs on datasets that already exist in your galaxy history.

**Comment by mestato** [comment]
I agree, the long term solution needs to separate file management from workflows. In the meantime, could we create a new Tripal Galaxy admin option to limit user upload file size and to specify that limit? We could put a 2Gb limit for now and that would help us get something live.

**Comment by Ferrisx4** [comment]
I like the idea of the 'dataset library'. Could it possibly be extended to show (with a bit of configuration) large files that already exist on the server that have been made available to all users of a certain workflow? For example, a Diamond workflow would show a list of genome/gene/protein files to run against. This would prevent large files from having to be re-uploaded.

**Comment by mestato** [comment]
The oft-used large file problem is addressed through site wide files. The Tripal site administrator can expose commonly used files (a BLAST database, a genome for mapping, etc) for users to select within a workflow. 

But I have the same concern about reuploading to Galaxy - even the site wide files stored once via Tripal are repeated reuploaded to Galaxy each time a user selects them. I opened a related issue on using data libraries to fix that problem: https://github.com/tripal/tripal_galaxy/issues/31

**Comment by MingChen0919** [comment]
for a temporary solution, in addition to having a 2G upload limit, we can add often used reference genomes as built-in datasets to the WSU galaxy (see https://galaxyproject.org/admin/data-preparation/).

**Comment by mestato** [comment]
I suggest moving additional comments relevant to the Galaxy built in data library conversation to that issue, https://github.com/tripal/tripal_galaxy/issues/31, and focusing on the data upload errors in this issue.

**Comment by spficklin** [comment]
The upload code part of Tripal, so this issue should be moved over to the Tripal issue queue for fixing.

**Comment by spficklin** [comment]
I'm leaving this open because it's a problem for us here though.

**Comment by spficklin** [comment]
Moved this over to the Tripal issue queue for resolution there.
