### ISSUE TITLE
`Undefined index: name` error when importing some workflows

### ISSUE THREAD

**Issue by MingChen0919** [tripal/tripal_galaxy#35]
When importing these two workflows:
https://galaxy.bioinfo.wsu.edu/u/mingchen0919/w/rnaseq-normalized-counts-cuffnorm-single-end
https://galaxy.bioinfo.wsu.edu/u/mingchen0919/w/rnaseq-normalized-counts-cuffnorm

I got this error:

```
Notice: Undefined index: name in tripal_galaxy_build_webform() (line 97 of /data/www/html/hardwoods_dev/drupal-7.52/sites/all/modules/custom/tripal_galaxy/includes/tripal_galaxy.webform.inc).
```

This two workflows worked fine if running directly on Galaxy.

**Comment by cwytko** [comment]
Is this the same issue as #36 ?

**Comment by spficklin** [comment]
Okay, I have pushed a fix for this. I can now import the workflow without the error appearing.  Although there are a lot of steps in that workflow and the progress bar looks bad. But that's a different issue. Can you test and let me know if you can now import the workflow?

**Comment by MingChen0919** [comment]
fixed
