### ISSUE TITLE
Call to undefined function dpm() error when adding workflow

### ISSUE THREAD

**Issue by NicHerndon** [tripal/tripal_galaxy#38]
I tryed to add a Galaxy workflow and received the following error message:
`Error: Call to undefined function dpm() in colleague_submission_alterations_node_insert() (line 7 of /var/www/Drupal/sites/all/modules/custom_modules/colleague_submission_alterations/colleague_submission_alterations.module).`

**Comment by MingChen0919** [comment]
the `dpm()` function is from the **devel** module. You can download and enable the module and try again.

**Comment by spficklin** [comment]
@NicHerndon This dpm() is not in the Tripal code... sometimes we forget to take them out, but this one looks like it's coming from some custom module named colleague_submission_alterations.

**Comment by NicHerndon** [comment]
I tried the following with no luck. Should I download the module in a different way?
`# drush dl tripal_galaxy`
`Install location /var/www/Drupal/sites/all/modules/tripal_galaxy already exists. Do you want to overwrite it? (y/n): y`
`Project tripal_galaxy (7.x-1.0-alpha1) downloaded to /var/www/Drupal/sites/all/modules/tripal_galaxy.                                                         [success]`
`# drush en tripal_galaxy`
`tripal_galaxy is already enabled.                                                                                                                             [ok]`
`There were no extensions that could be enabled.                                                                                                               [ok]`

**Comment by NicHerndon** [comment]
@spficklin I disabled the colleague_submission_alterations module, and was able to add the workflow. Thank you.
