### ISSUE TITLE
Some files on the drop down list of "User Uploaded Files" field don't exist, which causes an error

### ISSUE THREAD

**Issue by MingChen0919** [tripal/tripal_galaxy#39]
when I use a file from the "User Uploaded Files" drop down that actually does not exist in my **sites/default/files/tripal/users/[USER_ID]**, it causes the following error:

```
Uploading GCF_000005845.2_ASM584v2_genomic.fna.fasta...
Exception: failed creating formpost data in                          [error]
/data/www/html/hardwoods_dev/drupal-7.52/sites/all/modules/custom/tripal_galaxy/api/tripal_galaxy.api.inc:710
Stack trace:
#0
/data/www/html/hardwoods_dev/drupal-7.52/sites/all/modules/custom/tripal_galaxy/api/tripal_galaxy.api.inc(386):
tripal_galaxy_upload_file(Object(GalaxyInstance), '514',
'd4fa6959d18b946...', Array)
```

If i re-upload the file and run the workflow again, the workflow can go through without problem.

**Comment by spficklin** [comment]
Hey @MingChen0919 can you reproduce this problem?  Or, can you give us a series of steps we can use to see this problem on our end?  If not, can you describe the steps you wen through?    One item that confuses me is why the file didn't exist.  Did you uploaded it separate from the workflow or within the workflow?

**Comment by MingChen0919** [comment]
I think the problem is caused because some uploaded files expired and then get removed automatically, but they are not reflected in the drop-down list. for example: below is the content of my `defaults/files/tripal/users/1` directory:

```
.
├── 100H_4_0_S31_R1_001_combined.fastq
├── 100H_4_0_S31_R1_001_combined.fastq.md5
├── 100H_8_0_S37_R1_001_combined.fastq
├── 100H_8_0_S37_R1_001_combined.fastq.md5
├── 100M_emerald_6.5_Sample10_L1.R1.paired.trimmed.fq
├── 100M_emerald_6.5_Sample10_L1.R1.paired.trimmed.fq.md5
├── 100M_emerald_6.5_Sample10_L1.R2.paired.trimmed.fq
├── 100M_emerald_6.5_Sample10_L1.R2.paired.trimmed.fq.md5
├── dbSNP_138.hg19.vcf
├── dbSNP_138.hg19.vcf.md5
├── earlyFlower-rep1.counts.txt
├── earlyFlower-rep1.counts.txt.md5
├── earlyFlower-rep2.counts.txt
├── earlyFlower-rep2.counts.txt.md5
├── earlyFlower-rep3.counts.txt
├── earlyFlower-rep3.counts.txt.md5
├── expression_data.csv
├── expression_data.csv.md5
├── father.bam
├── father.bam.md5
├── hg19.twobit
├── hg19.twobit.md5
├── lateFlower-rep1.counts.txt
├── lateFlower-rep1.counts.txt.md5
├── lateFlower-rep2.counts.txt
├── lateFlower-rep2.counts.txt.md5
├── lateFlower-rep3.counts.txt
├── lateFlower-rep3.counts.txt.md5
├── mother.bam
├── mother.bam.md5
├── patient.bam
├── patient.bam.md5
├── Ppersica_298_v2.0.fa.md5
├── sample_table.txt
├── sample_table.txt.md5
├── temp/
│   ├── 100H_4_0_S31_R1_001_combined.fastq/
│   ├── 100H_8_0_S37_R1_001_combined.fastq/
│   ├── 100M_emerald_6.5_Sample10_L1.R1.paired.trimmed.fq/
│   ├── 100M_emerald_6.5_Sample10_L1.R2.paired.trimmed.fq/
│   ├── dbSNP_138.hg19.vcf/
│   ├── earlyFlower-rep1.counts.txt/
│   ├── earlyFlower-rep2.counts.txt/
│   ├── earlyFlower-rep3.counts.txt/
│   ├── expression_data.csv/
│   ├── father.bam/
│   ├── hg19.twobit/
│   ├── lateFlower-rep1.counts.txt/
│   ├── lateFlower-rep2.counts.txt/
│   ├── lateFlower-rep3.counts.txt/
│   ├── mother.bam/
│   ├── patient.bam/
│   ├── Ppersica_298_v2.0.fa/
│   ├── sample_table.txt/
│   ├── trait_data.csv/
│   └── V_corymbosum_scaffold_May_2013.fa/
├── trait_data.csv
├── trait_data.csv.md5
└── V_corymbosum_scaffold_May_2013.fa.md5
````

**Which does not contain the file `Cm_v2_pseudochr.fa(694.99MB)`**, but the drop-down list has this file displayed.
<img width="1272" alt="screen shot 2018-01-08 at 5 21 58 pm" src="https://user-images.githubusercontent.com/1262709/34695473-f953fcb2-f498-11e7-8e62-4ed37954603b.png">

**Comment by MingChen0919** [comment]
I don't know why only that some files get removed. if you would like to reproduce the error, you can manually delete a file in the `sites/default/files/tripal/users/[SOME_USER_ID]` directory and select that file in a workflow and then submit and invoke the workflow. that should give you the error.

**Comment by cwytko** [comment]
So this involves how the db table handles when files are stored when uploaded, when a file is manually deleted and **not** deleted through the Drupal/Tripal command/interface, then the db will still keep the entry despite the file actually being gone.
@spficklin How should we prevent a file that no longer exists despite being in the db tables.
