### ISSUE TITLE
Delete Galaxy Workflow Input file on Invoke

### ISSUE THREAD

**Issue by cwytko** [tripal/tripal_galaxy#47]
When a user presses the `submit` button on the tripal side to start the workflow, silently delete these file from the tripal server as they are only needed and used on the galaxy side

**Comment by spficklin** [comment]
I don't think files should be deleted after a workflow is invoked.  We have the file management system to let users remove their own files and files can be re-used on multiple workflows.   I'm marking this closed but if I have misunderstood please re-open.
