### ISSUE TITLE
mismatch between galaxy tool xml and tripal webform  for tool flagstat v2.0.1

### ISSUE THREAD

**Issue by MingChen0919** [tripal/tripal_galaxy#51]
Flagstat in Galaxy
<img width="558" alt="screen shot 2018-01-10 at 12 30 30 pm" src="https://user-images.githubusercontent.com/1262709/34794079-56fa42e4-f602-11e7-87f0-d51caff4af82.png">

Flagstat in Tripal
<img width="723" alt="screen shot 2018-01-10 at 12 30 19 pm" src="https://user-images.githubusercontent.com/1262709/34794080-5892e9da-f602-11e7-8820-01eb8464b40b.png">

**Comment by spficklin** [comment]
Hi @MingChen0919 I don't see what the problem is on this one.  Is it that in Galaxy it indicates output from step 6 and on the Tripal site it indicates output from step 7?  If that's the difference then this should be okay, because the steps on the Tripal side are offset by 1 because step 1 is the instructions.

**Comment by MingChen0919** [comment]
Sorry for the confusion. This is a webform and workflow mismatch issue. The flagstat tool on tripal site has an extra field "Optional Settings". When the workflow is viewed on Galaxy, it doesn't have the "Optional Settings" field. All alignment/mapping workflows use the flagstat tool, here is an example: https://github.com/statonlab/dibbs/blob/master/workflow-updates/hisat2-alignment_(paired_end).ga

**Comment by MingChen0919** [comment]
fixed in #80 and #83, waiting on confirmation on PR.

**Comment by spficklin** [comment]
I'm reopening as we may have to rework those pull requests.

**Comment by mestato** [comment]
My original complaint is that Tripal shouldn't create an "Optional Parameters" box that is empty of any content, its a waste of the users time to click on it. I'm not sure if it is a flagstat only issue, or a broader issue.

**Comment by MingChen0919** [comment]
This is a broader issue. This PR fixes this issue globally: not displaying optional settings if it is empty.

**Comment by MingChen0919** [comment]
hi @spficklin , i think this can be closed. The #102 fixed this issue.

**Comment by spficklin** [comment]
Okay, great!
