### ISSUE TITLE
error occurs when clicking 'Previous page' from Preview step

### ISSUE THREAD

**Issue by MingChen0919** [tripal/tripal_galaxy#52]
See the error message below:
```
Notice: Trying to get property of non-object in theme_webform_display_galaxy_pflist() (line 54 of /var/www/html/sites/all/modules/tripal_galaxy/includes/components/tripal_galaxy.galaxy_pflist.inc).
```

**Comment by spficklin** [comment]
@MingChen0919 I am not able to duplicate this problem.  Do you still see it?  This looks like an error specific to paired file workflows.

**Comment by MingChen0919** [comment]
No. I don't see this problem anymore. I just tested with both single and paired files workflow. Didn't see this problem. Maybe this has been fixed by someone? I think we can close this one.

**Comment by spficklin** [comment]
Sounds good.  Thanks for checking
