### ISSUE TITLE
text flow out out the fieldset name area

### ISSUE THREAD

**Issue by MingChen0919** [tripal/tripal_galaxy#53]
When the tool description is too long, the text flows out of the fieldset name box. see the comparison between tripal and galaxy.

<img width="1292" alt="screen shot 2018-01-10 at 1 56 53 pm" src="https://user-images.githubusercontent.com/1262709/34797818-846de850-f60e-11e7-8cc8-ba51d41fe1cc.png">

**Comment by spficklin** [comment]
I've noticed that too on some of the workflows.   Is it typical to have names for steps to be that long?   I would think that step names should be short and succinct and additional details could go in as notes? Is there another place to put those other details?

**Comment by MingChen0919** [comment]
The title includes the tool name and the tool description (same as in Galaxy). Some tool descriptions can be very long. Since we can edit the fieldset titles, this won't be a problem. So, I am closing this issue.

**Comment by spficklin** [comment]
What if we just put the tool name in the fieldset header bar and put the description inside the fieldset?

**Comment by MingChen0919** [comment]
that works. Alternatively, maybe we can just get rid of the description. We already have tool descriptions for each tool on the instruction page.
