### ISSUE TITLE
missing descriptions in several fields of tool rmarkdown_fastqc_report v2.0.0

### ISSUE THREAD

**Issue by MingChen0919** [tripal/tripal_galaxy#54]
<img width="1297" alt="screen shot 2018-01-10 at 4 16 06 pm" src="https://user-images.githubusercontent.com/1262709/34802323-f5b98146-f621-11e7-850b-928ab5c08b9b.png">

**Comment by spficklin** [comment]
Can you provide a link to this specific workflow so we can test?

**Comment by MingChen0919** [comment]
here is a workflow that uses the **fastqc report** tool: https://github.com/statonlab/dibbs/blob/master/workflow-updates/hisat2-alignment_(paired_end).ga

**Comment by MingChen0919** [comment]
closed as it is not an error.

**Comment by cwytko** [comment]
The concern is to have the descriptions presented as well

**Comment by MingChen0919** [comment]
This issue can be closed if #79 is accepted.
