### ISSUE TITLE
Can't launch workflow

### ISSUE THREAD

**Issue by NicHerndon** [tripal/tripal_galaxy#55]
$ drush trp-galaxy-invoke --submission=12
Launching workflow...
Exception: Unsupported content-type: text/html                                                                  [error]
Content:
HTTP/1.1 403 Forbidden
Server: nginx/1.10.2
Date: Thu, 11 Jan 2018 19:13:26 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
x-frame-options: SAMEORIGIN

{"err_msg": "Provided API key is not valid.", "err_code": 403001} in
/var/www/Drupal/sites/all/modules/tripal_galaxy/api/tripal_galaxy.api.inc:751
Stack trace:
#0 /var/www/Drupal/sites/all/modules/tripal_galaxy/api/tripal_galaxy.api.inc(360):
tripal_galaxy_get_history(Object(GalaxyInstance), 'TG-1-3-12-2018_...', Array)
#1 /var/www/Drupal/sites/all/modules/tripal_galaxy/tripal_galaxy.drush.inc(68):
tripal_galaxy_invoke_workflow('12')
#2 phar:///usr/local/bin/drush/includes/command.inc(422): drush_tripal_galaxy_trp_galaxy_invoke()
#3 phar:///usr/local/bin/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#4 phar:///usr/local/bin/drush/includes/command.inc(199): drush_command()
#5 phar:///usr/local/bin/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#6 phar:///usr/local/bin/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#7 phar:///usr/local/bin/drush/includes/startup.inc(458): drush_main()
#8 phar:///usr/local/bin/drush/includes/startup.inc(365): drush_run_main(false, '/', 'Phar detected. ...')
#9 phar:///usr/local/bin/drush/drush(114): drush_startup(Array)
#10 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#11 {main}

**Comment by spficklin** [comment]
Hi Nic,

Did you get this resolved? It looks as though the problem is a bad API Key:  "Provided API key is not valid."

**Comment by NicHerndon** [comment]
Since I'm using the [Galaxy API](https://docs.galaxyproject.org/en/latest/api_doc.html), I'm no longer using `trp-galaxy-invoke`.
