### ISSUE TITLE
need to annotate and export webform by directly editing webform components

### ISSUE THREAD

**Issue by MingChen0919** [tripal/tripal_galaxy#57]
When editing the fieldset title or field title from step 1 of a galaxy webform, the 'workflow_id' information is not populated into the database, which results in failure in running the workflow.

**Comment by MingChen0919** [comment]
directly editing a galaxy webform seems to break the workflow. To share a galaxy webform, it's recommended to export the intact webform to a json and edit the json file to annotate the webform, then import the edited webform to another tripal site.

i am going to label this as enhancement and put a low priority on this.

**Comment by spficklin** [comment]
@MingChen0919 which fields are you editing?   

In our online tutorial we indicate that not all fields should be edited (http://tripal.info/tutorials/v3.x/galaxy-add-workflow#toc-customize-the-submission-page-TZIAVjOf)  Are you editing only the **safe** fields?

**Comment by MingChen0919** [comment]
yes, I only edited the **safe** fields. I implemented the functionality that allows exporting workflows to a json file and annotating workflows on the json file. I am closing this for now.

**Comment by spficklin** [comment]
I'm reopening as I think we should take a look to see what went wrong.

**Comment by MingChen0919** [comment]
I think we editing workflows on tripal site is not a good idea. Fixes #77 and #79 enables detailed annotation and help information being pulled directly from Galaxy. This issue can be closed if those PRs are accepted.

**Comment by shawnawsu** [comment]
Those PRs were merged so I am closing this ticket.
