### ISSUE TITLE
workflow status info not showing on job queue table

### ISSUE THREAD

**Issue by MingChen0919** [tripal/tripal_galaxy#59]
<img width="1239" alt="screen shot 2018-01-14 at 2 01 44 pm" src="https://user-images.githubusercontent.com/1262709/34921195-af9736bc-f933-11e7-976b-7e25bc0b1a34.png">

**Comment by spficklin** [comment]
I've applied a fix for this.  To get these workflows to force a status update you can try the following:

drush trp-galaxy-status --submission=36 --force=1
drush trp-galaxy-status --submission=35 --force=1

Let me know if this fixes it for you.

**Comment by MingChen0919** [comment]
confirmed
