### ISSUE TITLE
webform for hisat2 alignment workflow is not correct

### ISSUE THREAD

**Issue by MingChen0919** [tripal/tripal_galaxy#60]
![Screen Shot 2018-01-22 at 9.41.28 PM](http://static.gitscout.com/0e299104718a0205779a30aeed13cbdbd8920a05123f6d02ed016f0b67b24bcb.png)

**Comment by spficklin** [comment]
@MingChen0919 which workflow is this?

**Comment by MingChen0919** [comment]
these two that use hisat2 tool:
1. https://github.com/statonlab/dibbs/blob/master/workflow-updates/hisat2-alignment_(paired_end).ga
2. https://github.com/statonlab/dibbs/blob/master/workflow-updates/hisat2-alignment_(single_end).ga

**Comment by spficklin** [comment]
@MingChen0919 I have just pushed a fix for this. Can you try re-importing your workflow and see if the problem is fixed.

**Comment by MingChen0919** [comment]
confirmed
