### ISSUE TITLE
tripal_html5_file_process

### ISSUE THREAD

**Issue by gdroc** [tripal/tripal_galaxy#61]
![capture d ecran 2018-01-30 a 14 42 25](https://user-images.githubusercontent.com/154846/35569245-007bd980-05cc-11e8-8d1e-50685c20b581.png)

When I click on the Next Page button, I have got the following message: 
Fatal error: Call to undefined function tripal_html5_file_process() 

In tripal_galaxy.form_elements.inc, I see this comment 👍 
  // We want to "inherit" the html5_file widget.
 
What does it mean? Does I need to install a new module?

**Comment by MingChen0919** [comment]
The function is defined in `tripal.module`. do you have the newest tripal?

**Comment by gdroc** [comment]
For now, I do not use the newest tripal version

**Comment by MingChen0919** [comment]
tripal galaxy works with both tripal 2 and tripal 3. Maybe you can check your **tripal.module** file to see if your version have the `tripal_html5_file_process()` function?

**Comment by gdroc** [comment]
I use the last stable version of tripal (7.x-2.1) and I can't found this function.

**Comment by spficklin** [comment]
Hi @gdroc .I'm just checking that this got resolved for you?

**Comment by spficklin** [comment]
BTW. The module is still in alpha mode so if you notice any other issues pleas feel free to let us know.
