### ISSUE TITLE
Expiration of Galaxy results leaves dangling "View Results" links

### ISSUE THREAD

**Issue by mestato** [tripal/tripal_galaxy#62]
When the results of a workflow expire and are erased on the Galaxy server, the "view results" link remains active on the Tripal side.

**Comment by spficklin** [comment]
Do you have Galaxy setup to automatically purge histories and workflow invocations after a certain period of time?

**Comment by mestato** [comment]
I imagine most Galaxy servers would have that setup (I'm checking with Heidi about the WSU one specifically).  Even if deletions are manual - ie a Galaxy admin is doing purges only when things get old - the Tripal module whill need to be able to detect that the links no longer go anywhere. So a user can see the job ran but now its expired.
