### ISSUE TITLE
Distinct Users when submitting a published workflow

### ISSUE THREAD

**Issue by cwytko** [tripal/tripal_galaxy#63]
When a user on Tripal submits a workflow, we default to using the admin's username and API key
This doesn't allow a user to trace back to their results to query once the file download links have expired

A proposal:
Silently add the user to the galaxy instance and associate that newly created user to tripal before invoking the workflow **or** check to see if the user already has an association to the galaxy server

This is going to be **necessary** if we are to have file distinction between users when adding existing files to a given workflow

**Comment by shawnawsu** [comment]
Hi @mestato, As I've gotten further along on this ticket I realized I didn't know how you were planning on accessing other user's workflows in Galaxy. I'm still new to the tool but I couldn't find a way to access other user's workflows without logging in as them and I image you wouldn't want to do that as it would be time-consuming.

**Comment by mestato** [comment]
I spoke to Ming and neither of us thinks this issue makes any sense. My thoughts...

"once the file download links have expired" -The links don't expire, the whole workflow history is expunged after a set number of days. Making a new user doesn't change that. 

"to have file distinction between users when adding existing files to a given workflow" - this isn't a problem. files are associated with individual histories, so even if two users upload different files with the same name, its not a problem.

"how you were planning on accessing other user's workflows in Galaxy" - if we did go down the route of making individual galaxy user accounts (and there are good data management reasons for doing so), then the workflows would be installed by an admin and made public. The users would still only be able to see and execute the public workflows made by the admin that are ported to the Tripal site.

So I'm closing.
