### ISSUE TITLE
User file association

### ISSUE THREAD

**Issue by cwytko** [tripal/tripal_galaxy#64]
Related to #63 

There needs to be an additional db table for figuring out what users are allowed to see what files

**Comment by spficklin** [comment]
Can you clarify what you mean by "see what files"?

**Comment by cwytko** [comment]
What files are visible to the user in terms of what files that particular user has added to the galaxy and therefore that user alone should be the only one seeing those files

**Comment by spficklin** [comment]
"Seeing" in Galaxy or in Tripal?

**Comment by cwytko** [comment]
Seeing in Tripal
