### ISSUE TITLE
Adding users to a galaxy server

### ISSUE THREAD

**Issue by cwytko** [tripal/tripal_galaxy#65]
When an admin is adding a new galaxy server, should there be a check on any users on that galaxy server and a prompt to the admin to add/associate users to the newly added server?

**Comment by cwytko** [comment]
Also should their be a page for the admin to add user access to certain galaxy servers so only certain ones are visible?

**Comment by spficklin** [comment]
Is this a request from a user or just a potential gotcha?

**Comment by spficklin** [comment]
I like the solution in #63 better.  We can revisit this if we get a specific request to do so.
