### ISSUE TITLE
Limit file size

### ISSUE THREAD

**Issue by mestato** [tripal/tripal_galaxy#73]
If a user submits a very large file to Galaxy (say 100k sequences for BLAST), it will potentially run for weeks or months on the Galaxy server. We need a way to warn users about medium to large files and block very large files. This probably needs to be workflow specific, but if a global solution is all we can get, then that's better than nothing.

**Comment by spficklin** [comment]
This would be application specific right?  Not necessarily size specific?

**Comment by mestato** [comment]
I would suggest workflow specific. For example, assembly of 100,000 RNASeq reads is small task that would complete in a few minutes, but BLAST'ing 100,000 reads against a large protein database could take a week. This is further dependent on Galaxy instance - Right now everything is single core on WSU for example but if you have a giant cluster that uses MPI maybe this isn't an issue. 

I suggest an admin can specify a file upload size limit for each input of a workflow, whatever makes sense for their set up. That should be custom enough for most use cases.

**Comment by mestato** [comment]
I am rethinking how we do this - we're now thinking we will give admins the ability to limit the size of individual file uploads, so not basing limits on workflows. Closing for now.
