### ISSUE TITLE
This link has expired. Please reload the job results page for uploaded links.

### ISSUE THREAD

**Issue by MingChen0919** [tripal/tripal_galaxy#76]
Some tools (e.g., the aurora_fastqc tool) have links in the output file that are linked to internal outputs from that tool. Clicking those links won't give access to the internal files and it show the message:

**This link has expired. Please reload the job results page for uploaded links.**

**Workflow for testing**:

[test-workflow.ga.zip](https://github.com/tripal/tripal_galaxy/files/2085581/test-workflow.ga.zip)

The inputs for this workflow can be any single end sequences in fastq format.

Once the job is complete, on the results page, click **aurora fastqc**->**View Results aurora fastqc**.

<img width="707" alt="screen shot 2018-06-08 at 2 30 58 pm" src="https://user-images.githubusercontent.com/1262709/41174620-a8da4ff0-6b28-11e8-97c0-2cb9a87d6f39.png">

Then go to the bottom of the html report, click any links under the Outputs section:

<img width="1041" alt="screen shot 2018-06-08 at 2 32 32 pm" src="https://user-images.githubusercontent.com/1262709/41174689-d93cff26-6b28-11e8-91e6-3e2483f4ae57.png">

**Comment by spficklin** [comment]
Hi @MingChen0919 I'm not able to reproduce this bug.  Also, I don't see an 'Aurora Fastqc' on the resluts page. Just 'FastQC'.  Am I using the right workflow?  I used the one you linked to above but it's been awhile since you posted that.

**Comment by MingChen0919** [comment]
Sorry for the confusing. It is **aurora_fastqc**. Did you use the workflow I attached on the comment? If yes, then you are using the right workflow.

**Comment by spficklin** [comment]
Yes I did. but none of the steps have the word Aurora.  Even if you click the link above and search for the word Aurora, there's nothing.

**Comment by spficklin** [comment]
PR Submitted for this. Can you please review?

**Comment by MingChen0919** [comment]
Please see my review comments at #105 , thanks!

**Comment by spficklin** [comment]
PR Fixed this.
