### ISSUE TITLE
When the value of an [Advanced Options] component is [Hide Advanced Options]

### ISSUE THREAD

**Issue by MingChen0919** [tripal/tripal_galaxy#84]
When the value of an **Advanced Options** component is **Hide Advanced Options**, we should not display this component to end users, because end users either don't see any advanced options nor able to edit it. 

<img width="704" alt="screen shot 2018-03-30 at 11 01 15 am" src="https://user-images.githubusercontent.com/1262709/38142434-47c85e00-340a-11e8-81ea-17faa5af5e0f.png">

**Comment by MingChen0919** [comment]
Fixed in #85

**Comment by spficklin** [comment]
I think this is fixed. Please comment if not.
