### ISSUE TITLE
Tripal Galaxy API Additions

### ISSUE THREAD

**Issue by shawnawsu** [tripal/tripal_galaxy#97]
This is a space for requests to the API.

**Comment by spficklin** [comment]
Add functions to get galaxy servers that have been "registered" with the site.

**Comment by spficklin** [comment]
We should add a way to submit a workflow through blend4php but with Tripal Galaxy API functions so that workflows invoked outside of the webform interface can still be tracked by Tripal.

**Comment by spficklin** [comment]
Closing this. AFter discussion with Nic we only have 1 funciton left we need and I'll create a new issue for it.
